# Generated by Django 5.2.3 on 2025-06-29 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Username must be at least 3 characters long.'), django.core.validators.MaxLengthValidator(15, message='Username cannot exceed 15 characters.')])),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Basic User',
                'verbose_name_plural': 'Basic Users',
                'ordering': ['username'],
            },
        ),
    ]
