from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, RegisterAPIView, LoginAPIView # Import new views

router = DefaultRouter()
router.register(r'users', UserViewSet) # Your existing UserViewSet registration

urlpatterns = [
    # Explicit paths for your desired authentication endpoints
    path('auth/register', RegisterAPIView.as_view(), name='register'),
    path('auth/login', LoginAPIView.as_view(), name='login'),

    # Include routes generated by your router for UserViewSet (e.g., /api/users/, /api/users/{pk}/)
    path('', include(router.urls)),
]
