"""Add password column to User

Revision ID: 2a7a93bb6b6c
Revises: 588f055d2425
Create Date: 2025-07-02 20:03:24.146950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7a93bb6b6c'
down_revision = '588f055d2425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_password_key'), type_='unique')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('users_password_key'), ['password'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
